name: Test
run-name: dummy-${{ inputs.stage }}
# command - count - motion
on:
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: Deploy to
        required: true
        options:
          - all
          - dev
          - test
          - prod
        #        default: all
      app_stack:
        type: string
        description: Application stack
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo something
        run: |
          echo "The inputs where ${{ inputs.stage }}-${{ inputs.app_stack }}"
