
name: Test

on:
  workflow_dispatch:
    stage:
      type: choice
      description: Deploy to
      options:
      - all
      - dev
      - test
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: echo something
      run: echo "something!"
