name: Test
run-name: dummy-${{ inputs.stage }}
# command - count - motion
on:
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: Deploy to
        required: true
        options:
        - all
        - dev
        - test
        - prod
        #        default: all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: echo something
      run: echo "something!"
